# Source: https://rawg.io/apidocs
games = [
	{ title: "The Legend of Zelda: Ocarina of Time", release_year: 1998, image: "https://media.rawg.io/media/games/3a0/3a0c8e9ed3a711c542218831b893a0fa.jpg", description: "The Legend of Zelda™: Ocarina of Time™ – one of the most critically acclaimed games ever made –returns on the Nintendo eShop for Wii U™. Set off on a legendary journey to stop Ganondorf, who has plunged Hyrule into darkness. Travel through time as child and adult Link™ and experience Hyrule in peace and war to save the world and protect theriforce. Your quest takes you through dense forests and across wind-whipped deserts. Swim raging rivers, climb treacherous mountains, dash on horseback across rolling hills, and delve into dungeons full of creatures that fight to the finish to put an end to your adventures. As Link, you&#39;ll also travel through time to solve puzzles, save friends, and right Ganondorf&#39;s wrongs with the help from your trusty Ocarina of Time and the mysterious youth, Sheik." }, # Platforms: Nintendo 64, Nintendo DS, Publishers: Nintendo
	{ title: "The Legend of Zelda: Breath of the Wild", release_year: 2017, image: "https://media.rawg.io/media/games/cc1/cc196a5ad763955d6532cdba236f730c.jpg", description: "The Legend of Zelda: Breath of the Wild is an adventure game developed by Nintendo. It is the nineteenth installment in the series. After awakening from a hundred year sleep, memoryless Link hears a mysterious female voice that guides him to a destroyed kingdom of Hyrule. He finds a Wiseman who says that a ruthless creature, Calamity Ganon, was imprisoned for 100 years. Even though the creature is trapped, it is still gaining power. Link sets out to kill Ganon before he frees himself and destroys the world. In contrast to the previous titles in the series, Breath of the Wild the player to explore a vast open world. At the beginning of the game, a small tutorial is given to the players and they are free to travel the world at the pace they see fit. Link can climb almost every surface in the world, search for new equipment, cook food to restore health. Fast travel to certain places in the world is also available for the players. The world is highly interactive. For example, trees can be chopped down in order to make fire, or Link can use his shield as a snowboard." }, # Nintendo, Wii U, Switch
	{ title: "Super Mario Odyssey", release_year: 2017, image: "https://media.rawg.io/media/games/267/267bd0dbc496f52692487d07d014c061.jpg", description: "Super Mario Odyssey is a 3D platform game, a part of Nintendo’s Super Mario series. The game follows Mario on his quest to save Princess Peach from her forced marriage with Bowser. The game starts with Mario fighting Bowser on its aircraft. Bowers knock Mario off the ship and shreds his cap into pieces. Mario awakens in the Cap Kingdom inhabited with hat-like spirits and befriends one of them named Cappy. It turns out, Bowser also kidnapped Cappy’s sister Tiara, and now the heroes must chase Bowser through several kingdoms to save Peach and Tiara. The gameplay of Super Mario Odyssey draws inspiration from Super Mario 64 and Super Mario Sunshine. The game consists 17 levels (named as “kingdoms”). In most of them, your goal is to collect a certain amount of Power Moons. Collecting enough of them allows the player to progress to the next kingdom. Some moons can be found in different parts of the level or acquired as a reward for completing certain tasks or challenges. The Mario’s moveset mostly resembles that of Super Mario 64 and includes wall jumps, triple jumps, somersaults, long jumps, rolling on the ground. The main new gameplay feature is that Mario can throw his hat to create temporary platforms, grab objects, attack enemies, or possess them. Possessing enemies gives you new moves and sometimes is necessary to reach certain parts of the level." }, # Nintendo, Switch
	{ title: "Halo: Combat Evolved", release_year: 2001, image: "https://media.rawg.io/media/games/abf/abffd94ed6fe34027c720bee593c06d2.jpg", description: "GAME-PLAY ALERT: This game has been fully tested to successfully play on your Xbox 360 console. However, in some cases, you may see some minor irregularities with audio/video for brief periods. For more details, see www.xbox.com/xboxoriginals. Halo® is a sci-fi shooter that takes place on a mysterious alien ring-world. Packed with combat, Halo will have you battling on foot, in vehicles, inside and outdoors with Alien and Human weaponry. Your objective: to uncover Halo's horrible secrets and destroy mankind's sworn enemy, the Covenant." }, # Microsoft Game Studios, Xbox, PC, Xbox 360, Xbox One
	{ title: "Mass Effect 2", release_year: 2010, image: "https://media.rawg.io/media/games/3cf/3cff89996570cf29a10eb9cd967dcf73.jpg", description: "Mass Effect II is a sequel to Mass Effect one, following the story of Captain Shepard in his or her journey in saving the Galaxy from Reapers. Just after the fight against Saren, Shepard dies and drifts in open space. Being collected by Cerberus and the lead man, The Illusive Man, Shepard has to investigate attacks on human colonies around the Milky Way, and discover that now the Reapers using some new insectoid called the Collectors. \r\n\r\nYou can choose from different classes to play, for example, a Soldier, Adept or Vanguard. A cover system is the main mechanic in the fight, as you have to think about fighting your enemy strategically. Your talents have a global CDR, so choose wisely. With one little addition, now your weapon has a loaded magazine of bullets, and you can run out of ammo if not using your weapon properly. \r\n\r\nBioWare sticks to the tradition of dialogue and reputation system, as your actions still affect your position in the world. If you act like a hero and help everyone you meet, people will like you and your reputation will be Paragon. Do the exact opposite and a Renegade. Whom will you be?" }, # Electronic Arts, Playstation 3, Xbox 360, PC
	{ title: "The Legend of Zelda: Twilight Princess", release_year: 2006, image: "https://media.rawg.io/media/games/d95/d950e5b8f44716cef0eee33f04b8cb54.jpg", description: "When an evil darkness enshrouds the land of Hyrule, a young farm boy\nnamed Link must awaken the hero – and the animal – within. When Link\ntravels to the Twilight Realm, he transforms into a wolf and must scour\nthe land with the help of a mysterious girl named Midna. Besides his\ntrusty sword and shield, Link will use his bow and arrows by aiming with\nthe Wii Remote controller, fight while on horseback and use a wealth of\nother items, both new and old.\n\nThe Legend of Zelda: Twilight Princess is part of the Nintendo\nSelects family of games—great titles enjoyed by millions, now a great\nvalue at just $19.99 MSRP* each.\n\nFeatures\n\nArm Link: The Wii Remote and Nunchuk controllers are used for a\nvariety of game activities from fishing to projectile-weapon aiming.\nThe game features incredibly precise aiming control using the Wii\nRemote controller. Use the controllers for sword swings, spin attacks\nand shield shoves.\n\nThrilling Adventure: Players ride into battle against troops of\nfoul creatures and wield a sword and shield with the Wii Remote and\nNunchuk controllers, then take on massive bosses that must be seen to\nbe believed.\n\nMind & Muscle: Many puzzles stand between Link and the\nfulfillment of his quest, so players must sharpen their wits as they\nhunt for weapons and items.\n\n*MSRP: Manufacturer's Suggested Retail Price. Actual price may vary. See\nretailer for details." }, # Nintendo, GameCube, Wii
	{ title: "The Elder Scrolls V: Skyrim", release_year: 2011, image: "https://media.rawg.io/media/games/e9c/e9cbc91e2090638ddab6ae0b3d334f90.jpg", description: "The fifth game in the series, Skyrim takes us on a journey through the coldest region of Cyrodiil. Once again player can traverse the open world RPG armed with various medieval weapons and magic, to become a hero of Nordic legends –Dovahkiin, the Dragonborn. After mandatory character creation players will have to escape not only imprisonment but a fire-breathing dragon. Something Skyrim hasn’t seen in centuries.\r\nAfter Oblivion, the magic system was reworked, in order to show players more aggressive and direct combat. As a Dragonborn, your character will be able to use the powerful magic of dragon shouts, powered, upgraded and researched with the souls of the dragons that will be randomly encountered by players, while traveling. Hundreds of sidequests will invite players to discover every part of the newly introduced land. Aside from already filled with guilds, Daedra and steampunk Dwemer ruins, Skyrim has additional DLC content that not only brings Solstheim island and vampire conclave but gives players the ability to build their own homes, instead of buying pre-made ones." }, # Bethesda , Xbox 360, Playstation 3, PC, Xbox One, Playstation 4, Switch
	{ title: "Halo 2", release_year: 2004, image: "https://media.rawg.io/media/games/0c9/0c98889aa28b7c27474be0156961bee2.jpg", description: "The Covenant alien race threatens to destroy all humankind, and the only thing standing in its way is Master Chief, a genetically enhanced supersoldier. Master Chief returns in Halo 2, which features new vehicles, weapons, environments, and more. This time, you can interact with your environment, wield two weapons at the same time, board opponents' vehicles, and even switch sides to play the role of a Covenant Elite." }, # Microsoft Game Studios, Xbox, Xbox One
	{ title: "The Legend of Zelda: A Link to the Past", release_year: 1991, image: "https://media.rawg.io/media/screenshots/321/321d35cf08c62bc86efc8f7fa6d33bef.jpg", description: "Return to an age of magic and heroes! When an evil magician named \n      Agahnim begins kidnapping young maidens in Hyrule in a quest to break \n      the imprisoning seal on Ganon, a young boy named Link is called upon to \n      stop him. Link must venture into twisting mazes, dungeons, palaces and \n      shadowy forests as he searches for the maidens and Princess Zelda. \n      Traversing both Light and Dark Worlds, he must navigate eight dark \n      dungeons, fighting evil enemies and huge bosses. Help our hero prevent \n      Ganon and Agahnim from shattering Hyrule forever. Whether you are a \n      young knight, a heroine-in-training or a seasoned warrior, The Legend of \n      Zelda: A Link to the Past will delight!\n    This game is only playable in 2D.This classic game is part of the Virtual Console service, which brings you great games created for consoles such as NES™, Super NES™ and Game Boy™ Advance. See more Virtual Console games for Nintendo 3DS." }, # Nintendo, Super Nintendo Entertainment System
	{ title: "The Legend of Zelda: Link's Awakening", release_year: 1993, image: "https://media.rawg.io/media/games/a1b/a1b2af4caa3c61f9922431baf1fca447.jpg", description: "A high-seas voyage takes a dangerous turn when Link&#39;s ship is destroyed by a furious storm, and he washes ashore on the mysterious island of Koholint. Link learns that the only hope he has of returning home depends on awakening the mythical Wind Fish, who slumbers within a giant egg atop the island&#39;s highest peak. But who is the Wind Fish? How do you wake it? And what will happen when it awakes?  Lead Link on an incredible adventure as you explore uncharted lands,   meet amazing new friends and foes, and unravel the mystery of the Wind Fish." }, # Nintendo, Game Boy
	{ title: "Mario Brothers", release_year: 1983, image: "https://media.rawg.io/media/screenshots/f22/f22857f426275f7a09d865a2ad2376b9.jpg", description: "Mario and Luigi bring the POW! in this classic arcade game!\n\nMario and Luigi are doing some underground plumbing when all sorts of\nstrange creatures come flying out of the pipes. Help the two brothers\nclear stages by collecting coins and avoiding getting hit by enemies.\nCrabs, turtles, and fighter flies must be cleared out by jumping\nunderneath the platform they step on and then kicking them away. But\nbeware! Just when you think you got rid of them, they come back for\nmore! Play alone or with a friend. Either way, this is one underground\nclassic you will want to play time and time again." }, # Nintendo, Nintendo Entertainment System
	{ title: "Super Mario Brothers", release_year: 1985, image: "https://media.rawg.io/media/games/154/154fea9689109f26c49c6a2db6263ef9.jpg", description: "Mario and Luigi star in their first ever Mushroom Kingdom adventure! Find out why Super Mario Bros. is instantly recognizable to millions of people across the globe, and what made it the best-selling game in the world for three decades straight. Jump over obstacles, grab coins, kick shells, and throw fireballs through eight action-packed worlds in this iconic NES classic. Only you and the Mario Bros. can rescue Princess Toadstool from the clutches of the evil Bowser. \r\n\r\nFor more than 25 years, the Super Mario series has conquered the charts and won the hearts of fans the world over. Now you can discover - or rediscover - the original game that made Mario a household name.\r\n\r\nRun and jump with Mario or Luigi through caves and castles, down pipes and across platforms, and face off against Bowser to rescue your beloved Princess Peach.\r\n\r\nIt may be more than a quarter of a century old, but Super Mario Bros. is still as enchanting as ever!" }, # Nintendo, Nintendo Entertainment System
	{ title: "Diablo III", release_year: 2012, image: "https://media.rawg.io/media/games/a27/a275556fab1a6acaded4cedad0f9dc80.jpg", description: "The third Diablo returns you to the world of Sanctuary, once again invaded by the demons. Twenty years after the ending of Diablo II, a star has fallen on the city of New Tristram, spawning hordes of undead monsters that the player must defeat. As usual in Diablo series, the game has a trademark dark fantasy atmosphere and is mostly set in gloomy dungeons.\r\nThe basic gameplay features are the same as in previous Diablo games, but there are many subtle changes. The player can choose one of six character classes (a seventh is available with an expansion). Each class has its unique abilities and class-specific quests. Unlike its predecessors, which used isometric 2D graphics, Diablo III uses 3D, however, it preserves the familiar top-down view. The dungeons are randomly generated and have destructible environments, thanks to the new graphics engine. There’s a new mechanic Skill Runes that is used to improve the character’s skills.\r\nOnline multiplayer is available through Battle.net. There are both a co-op mode and a PvP mode called Brawling. The players can create hardcore characters who face permadeath if killed. Even in the single-player mode, Diablo II requires a stable internet connection, because of DRM restrictions." }, # Blizzard Entertainment, Switch, Playstation 4, Xbox One, Playstation 3, Xbox 360, PC
	{ title: "Duck Hunt", release_year: 1984, image: "https://media.rawg.io/media/screenshots/585/5855538528e7881c6f7540779504e377.jpg", description: "I made this game a while back and finally decided to finish it, it's a simple duck hunt game." }, # Nintendo, NES
	{ title: "Call of Duty 4: Modern Warfare", release_year: 2007, image: "https://media.rawg.io/media/games/9fb/9fbaea2168caea1f806546dfdaaeb1da.jpg", description: "The fourth installment of a popular series, Call of Duty 4: Modern Warfare is split into two different, gameplay-wise, parts. The single-player campaign invites players to go through the episodic story, where players control six different characters. And even though the stories are taking place in different locations, the events of the campaign are happening simultaneously, creating the sense of urgency and painting a large-scale picture of the events.\r\nMultiplayer side of things in the Call of Duty series has been more popular among the players. A lot of features, not present in the single-player campaign, will be available to the player, such as a killstreak mechanic, that rewards players for killing multiple enemies without dying. Multiplayer maps consist of team-based and deathmatch based game modes, where players take on the objectives in order to complete the map mission or to obtain the largest amount of kills. Depending on how well the player does, they will be rewarded with experience points, which will allow them to level up and unlock new weapons, abilities, and perks for the playable classes." }, # Activision, Playstation 3, Xbox 360, PC, Wii
	{ title: "Sonic the Hedgehog", release_year: 1991, image: "https://media.rawg.io/media/screenshots/8a6/8a6c27f641d5d55a2b6dc8ffd5629ae2.jpg", description: "Sonic The Hedgehog is a 2D platform game, the first installment in Sega’s Sonic the Hedgehog series. \n\n###Plot \nThe game takes place on South Island and follows Sonic — an anthropomorphic blue hedgehog. The game’s antagonist, a brilliant but insane scientist Dr. Robotnik attempts to take possession of the power of six Chaos Emeralds by entrapping South Island’s animal inhabitants inside hostile robots. Sonic decides to hinder Robotnik’s plans by freeing animals and collecting the emeralds himself.  \n\n###Gameplay \nThe game consists of six zones each of which is divided into three acts. In the first two acts, your goal is to reach the finish while the third act ends with a boss fight against Dr. Robotnik. After completing the sixth zone, you enter the Final Zone which consists of one act and the final battle against Robotnik. The level in the game is usually relatively roomy and implicate various ways of completing. The gameplay is centered on Sonic’s ability to run at high speed. Thereby the levels involve many slopes, loops, springs. Sonic can use Spin Attack to attack enemies or destroy certain obstacles.\nThe Spin Attack can be activated by gaining high speed while rolling on the ground or jumping. The players’ health depends on the main collectibles of the game – golden rings placed throughout the levels and collecting one hundred of them gives you an extra life. Also, as long as Sonic has at least one ring, upon getting hit he scatters rings instead of losing a life." }, # Sega, Sega Genisis
	{ title: "Sonic the Hedgehog 2", release_year: 1992, image: "https://media.rawg.io/media/screenshots/50a/50a5ff62488509688cd51845eb9defbd.jpg", description: "Sonic the Hedgehog 2 is a platform game, the second installment in Sega’s Sonic the Hedgehog series.  \n\n###Plot \nThe story shares many similarities with the previous game. Once again, Sonic must halt Dr. Robotnik’s plan on collecting six Chaos Emeralds and using their power to take over the world. This time, Robotnik build a space station called Death Egg and the events take place mostly on West Side Island. The game also introduces Tails – Sonic’s best friend and important character for the series. \n\n###Gameplay \nGameplaywise the game is very similar to its processor. The game consists of eleven zones.\nAll zones, except the final one, are divided into two or three acts. In each act, your goal Is either to reach the finish of the level or to defeat a boss. The gameplay revolves around Sonic’s ability to run at high speed. The levels involve many objects that help Sonic gain high speed such as slopes, loops, and springs. Sonic can attack enemies and break certain obstacles by using Spin Attack. Like in previous game Spin Attack activates by gaining high speed while rolling on the ground or jumping but Sonic the Hedgehog 2 introduces new gameplay mechanic – Spin Dash. Pressing down and jump while stationary results in Sonic curling in a ball and then upon releasing the button launches launching forward at high speed. The game supports co-op multiplayer in which one player takes the role of Sonic and other plays as Tails." }, # Sega, Sega Genisis
	{ title: "Super Smash Bros", release_year: 1999, image: "https://media.rawg.io/media/screenshots/19e/19ef3f86f84a7b42fa929676c6d1ed6b.jpg", description: "Mario! Link! Samus! Pikachu! All of your favorite Nintendo characters\nare back, along with plenty of new faces, in Super Smash Bros. for Wii\nU, the next entry in the beloved Super Smash Bros. series. Up to four\nplayers can battle each other locally or online across beautifully\ndesigned stages inspired by classic Nintendo home console games. With a\nvariety of control options and amiibo compatibility, the timeless Super\nSmash Bros. battles come alive. Compete with classic players from the Super Smash Bros. series, along\nwith new challengers like Mega Man, Little Mac or newly announced\nPalutena, the Goddess of Light from the Kid Icarus games.\n\nFor the first time, players can even compete as their own Mii\ncharacters.\n\nUse a variety of control methods during the high-energy and\naction-filled battles, including Nintendo GameCube controllers – the\nlongtime controller of choice for hard-core Super Smash Bros. players." }, # Nintendo, Nintendo DS, Nintendo 64
	{ title: "Silent Hill", release_year: 1991, image: "https://media.rawg.io/media/games/15d/15db2360d1130ba8c10573586588b0bd.jpg", description: "Silent Hill is a survival horror video game for the PlayStation published by Konami and developed by Team Silent, a group in Konami Computer Entertainment Tokyo. The first installment in the Silent Hill series, the game was released in North America in January 1999, and in Japan and Europe later that year. Silent Hill uses a third-person view, with real-time rendering of 3D environments. To mitigate limitations of the console hardware, developers liberally used fog and darkness to muddle the graphics. Unlike earlier survival horror games that focused on protagonists with combat training, the player character of Silent Hill is an \"everyman\".\nThe game follows Harry Mason as he searches for his missing adopted daughter in the eponymous fictional American town of Silent Hill; stumbling upon a cult conducting a ritual to revive a deity it worships, he discovers her true origin. Five game endings are possible, depending on actions taken by the player, including one joke ending.\nSilent Hill received positive reviews from critics on its release and was commercially successful. It is considered a defining title in the survival horror genre, and is also considered by many to be one of the greatest video games ever made, moving away from B movie horror elements, toward a psychological style of horror emphasizing atmosphere." }, # Konami, Playstation
	{ title: "Silent Hill 2", release_year: 2001, image: "https://media.rawg.io/media/games/003/0033ae7d21418ff5a7807ab2c7d90247.jpg", description: "Silent Hill 2 is an action, shooter and adventure game developed by Creature Labs and Team Silent. It came out on 24-09-2001. It was published by Konami. The game is rated as \"Exceptional\" on RAWG. You can play Silent Hill 2 on PC and PlayStation 2. It was produced by Akihiro Imamura. It was directed by Masashi Tsuboyama. It was scored by Akira Yamaoka." }, # Konami, Playstation 2
	{ title: "Silent Hill 3", release_year: 2003, image: "https://media.rawg.io/media/games/594/59415e7fe99545bb303c108b19f38667.jpg",description: "Silent Hill 3 is an action game developed by Konami Computer Entertainment Japan. It was originally released in 2003. Konami published the game. Most rawgers rated the game as \"Exceptional\". Silent Hill 3 is available on PC and PlayStation 2. Akira Yamaoka produced the game. Kazuhide Nakazawa directed the game. It was scored by Akira Yamaoka." }, # Konami, Playstation 2
	{ title: "Crazy Taxi", release_year: 1999, image: "https://media.rawg.io/media/games/97a/97a5fee8bba1189f70a9874171f45195.jpg", description: "Crazy Taxi is the renewed version of arcade machine title of the same name that was released in 1999. It’s a taxi driver simulator. The goal of the game is to deliver passengers to their destinations, performing numerous tricks. The game also features 16 mini-games. Crazy Taxi follows the classic mechanics of score games: you need to get from a passenger as much money as possible. In the beginning you can choose a driver and a car; their stats are quite similar with slight differences in speed and turning. To raise your tips you need to reach the destination on time. To earn extra money you can perform multiple tricks, including drifts, jumps, near-misses, and combos of these moves. Driving through the city isn’t that easy as it seems to be. There are numerous obstacles in your way, such as frustratingly slowly buses, that make you take risks during your maneuvers on the road. Moreover, the amount of potential passengers is limited: once you pick up a person, it’s unavailable for the rest of the game." }, # Sega, Dreamcast, GameCube, Playstation 2
	{ title: "Contra", release_year: 1987, image: "https://media.rawg.io/media/screenshots/79f/79f15eeda71f7534d58bacc55ae50ec0.jpg", description: "Single Player, Live Multiplayer 1-2, HD (High Definition). Relive the fun of this arcade classic! Help Lance and Bill rid the world of Red Falcon and all its alien minions! The full version includes access to all levels, Co-op multiplayer modes, a range of challenging achievements, and the ability to see how your scores compare to others!" } # Konami, NES
]

consoles = [
	{ name: "Game Boy" },
	{ name: "GameCube" },
	{ name: "Nintendo Entertainment System" },
	{ name: "Super Nintendo Entertainment System" },
	{ name: "Nintendo 64" },
	{ name: "Nintendo DS" },
	{ name: "Wii" },
	{ name: "Wii U" },
	{ name: "Nintendo Switch" },
	{ name: "Playstation" },
	{ name: "Playstation 2" },
	{ name: "Playstation 3" },
	{ name: "Playstation 4" },
	{ name: "Xbox" },
	{ name: "Xbox 360" },
	{ name: "Xbox One" },
	{ name: "Sega Genisis" },
	{ name: "Dreamcast" },
	{ name: "Other OS" }
]

publishers = [
	{ name: "Nintendo" },
	{ name: "Activision" },
	{ name: "Rockstar Games" },
	{ name: "Microsoft Game Studios" },
	{ name: "Sega" },
	{ name: "Valve" },
	{ name: "2K Games" },
	{ name: "Sony Computer Entertainment" },
	{ name: "Electronic Arts" },
	{ name: "Bethesda Software" },
	{ name: "Konami" }
]

games.each do |game|
	Game.find_or_create_by(title: game[:title], release_year: game[:release_year], image: game[:image], description: game[:description])
end
